### ISSUE TITLE
Some readme corrections

### ISSUE THREAD

**Issue by AMDmi3** [digitalist/systemdrop#1]
- `pkg-info` -> `pkg info`. Same thing actually, but the latter is canonical
- env is `/usr/bin/env`, not `/bin/env`
- there is unversioned python executable (`/usr/local/bin/python`), installed by the lang/python port. It's still good idea to explicitely use python2/python3 in shebangs though.

**Comment by digitalist** [comment]
thanks, I updated readme, though I did not have unversioned /usr/local/bin/python in my install (or maybe I managed to delete it?)

**Comment by AMDmi3** [comment]
> thanks, I updated readme, though I did not have unversioned /usr/local/bin/python in my install (or maybe I managed to delete it?)

You need to install `lang/python` for it (which you usually have to do manually as no ports depend on it). You've already mentioned that, and I've missed it. Elaborating, there are:

* `lang/python27`, `lang/python34`, `lang/python35`, `lang/python36` which are "real" python ports and these install 2-component versioned binaries (e.g. `python2.7`, `python3.6`),
* `lang/python2`, `lang/python3` which only install a set of 1-component versioned links `python2 -> python2.7`, `python3 -> python3.6`
* `lang/python` which only install a set of unversioned links (`python` -> `python2`)

**Comment by digitalist** [comment]
thanks, I'll do an update on this soon.

btw, I know this is not a support thread, but seeing you have a big experience with freebsd, maybe you can help me - is there some sane way to upgrade freebsd 11 to 12 current? Something like a standard procedure to change releases?

**Comment by AMDmi3** [comment]
The standard procedure is [freebsd-update](https://www.freebsd.org/doc/handbook/updating-upgrading-freebsdupdate.html), but it only supports releases, so it cannot be used to update to 11-STABLE or 12. For the latter, you'll have to [build from source](https://www.freebsd.org/doc/handbook/makeworld.html), but be aware of [implications](https://www.freebsd.org/doc/handbook/current-stable.html) of using untested development code. Why'd you need to switch to 12-current?

**Comment by digitalist** [comment]
hybrid graphics mostly. I have this monster combination of gpu+intel on my laptop

**Comment by AMDmi3** [comment]
Oh. I too use 12 for that on laptop, although that's for just newer intel support, fortunately I've never had to work with hybrid stuff. I've built from https://github.com/freebsd/freebsd-base-graphics (the procedure is the same), but afaik now you can just build normally from SVN and install `graphics/drm-next-kmod`.
